#!/bin/bash
set -e

source environment.sh

FLYWHEEL_BASE=/flywheel/v0
IN=$FLYWHEEL_BASE/input
OUT=$FLYWHEEL_BASE/output
TMP=/tmp

# the following lets output show on stdout and stderr, and also
# redirects them to files that will appear in the output.
# combines http://stackoverflow.com/a/692407 and http://stackoverflow.com/a/11886837
exec > >(tee -i $OUT/stdout.log) 2> >(tee -i $OUT/stderr.log >&2)

cd $TMP

RAW_NATIVE=$IN/native/*
NATIVE_BASENAME=$(basename $RAW_NATIVE)
NATIVE_WITHOUT_EXT="${NATIVE_BASENAME%%.*}"

mkdir $TMP/processed-native
NATIVE=$TMP/processed-native/$NATIVE_BASENAME
# fix nifti header issue
python $FLYWHEEL_BASE/fix_nifti.py $RAW_NATIVE $NATIVE

# converting input nifti to AFNI
3dcalc -a $NATIVE -prefix $NATIVE_WITHOUT_EXT -expr 'a'

# do align and warp
$FLYWHEEL_BASE/align.csh $NATIVE_WITHOUT_EXT+orig $IN/standard/* $IN/warp_target/*

# cleanup to avoid ambiguity in glob expressions below
rm __tmp_*

# convert output to nifti
for result in *.HEAD; do
  3dAFNItoNIFTI $result
  mv $(@GetAfniPrefix $result).nii $OUT
done

# copy to output directory
mv *_al2std_mat.aff12.1D $OUT
mv *_inv.aff12.1D $OUT
mv *_warp2std.nii.gz $OUT
mv *_WARP.nii.gz $OUT
